// Mocks generated by Mockito 5.0.15 from annotations
// in business/test/app/actions/choose_image_action_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:business/business.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Repository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepository extends _i1.Mock implements _i2.Repository {
  MockRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.ImageState>> getPhotos({int? page}) =>
      (super.noSuchMethod(Invocation.method(#getPhotos, [], {#page: page}),
              returnValue:
                  Future<List<_i2.ImageState>>.value(<_i2.ImageState>[]))
          as _i3.Future<List<_i2.ImageState>>);
  @override
  String toString() => super.toString();
}
